CREATE TABLE [Student](
	StudentID VARCHAR(10) PRIMARY KEY,
	StudentName NVARCHAR(30) NOT NULL,
	gender BIT,
	DoB DATE NOT NULL,
	Address VARCHAR(30) NOT NULL	
)
CREATE TABLE [Course] (
	CourseID INT PRIMARY KEY,
	CourseName NVARCHAR(30) NOT NULL
)
CREATE TABLE [Lecturer] (
	LecturerID INT PRIMARY KEY,
	LecturerName NVARCHAR (30) NOT NULL
	)
	CREATE TABLE [Group] (
	GroupID VARCHAR(10) PRIMARY KEY,
	GroupName NVARCHAR(30) NOT NULL
)
	CREATE TABLE [Group_student](
	StudentID VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES [Student](StudentID),
	GroupID VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES [Group](GroupID)
	)


